### PR TITLE
Added ability to pass *.shen files on command line

### PR DESCRIPTION
**Pull request by rkoeninger**
Test suite now runs on CI.
Also provided definition of `*sterror*`.

### CODE REVIEW

**Comment by tizoc** [comment]
Good. I'm still thinking about what to do about batch runs and command line arguments. Something that is good for al ports, to avoid having N implementations.

Btw, one thing I do in shen-scheme is to silence all output:

https://github.com/tizoc/shen-scheme/blob/master/shen/extensions/common.shen#L4-L6
and
https://github.com/tizoc/shen-scheme/blob/master/shen/runner.sld#L9-L11

**Comment by rkoeninger** [comment]
I just made it act like ShenSharp. I'll try to do the same for shen-sbcl and get the tests running in CI there. These can later be adapted to use the common interface referred to in https://github.com/Shen-Language/shen-sources/issues/4.

How would load files correctly using `shen.eval-without-macros`?

**Comment by tizoc** [comment]
@rkoeninger the Shen reader already expands the code using macros, thats why `eval-without-macros` is enough.

**Comment by rkoeninger** [comment]
Oh, I see.

Maybe that's something we could do in shen-sources - have a `*verbose*` flag that could be turned off or on that spits out extra information like load time, the result of each expression, typechecking, etc. 

I'm going to go ahead and merge this and make similar changes to shen-sbcl.

**Comment by tizoc** [comment]
Yes, this is the stuff I want to solve for the next release.

What I'm leaning on so far is:

- A new `*command-line*` global (or `*system-argv*` or whatever, containing ARGV (and like with ARGV, the first element would be the executable name)
- A new entry point for scripts (it takes a file, and loads it silently). This entry point could take the ARGV list as its argument, removing the need for the global.
- Maybe update the parser so that it support posix shebangs (so that `#!/bin/env shen` works), but I'm not really sure about this one yet, maybe it could be handled by an external tool.

What Neal implemented in his fork could be added to the wiki or as a library for anyone who wants to use it: https://github.com/NHALX/Shen-SBCL/commit/7ea89c97fce3f1d4e4427c5ef2c46eeaad7fa7b4#diff-49a277b40f2c51d36f1c5fc57ab0bf87R70

Anyway, if you have ideas, just comment on the shen-sources repo issues.

**Pull request merged**
